# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               XYZ
tagline:             '...'
description:         '......'
url:                 https://tejawha.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Tejawha
  url:               https://twitter.com/xxyzzzzz
  email:             tejawha@gmail.com

# Custom vars
version:             1.0.0
